### ISSUE TITLE
cannot access web server from host

### ISSUE THREAD

**Issue by PatGendre** [IsraelHikingMap/graphhopper-docker-image-push#15] opened 2022-02-16 14:26 UTC
Thanks for maintaining this GH docker image :-)
I tried to use it, I could adapt the command line so as to feed GH with my own pbf data, 
the docker run command makes the jetty web server up and running,
but I cannot access it from the host locally.

`docker run -p 8989:8989 --env JAVA_OPTS="-Xmx1g -Xms1g -Ddw.server.application_connectors[0].bind_host=0.0.0.0 -Ddw.server.application_connectors[0].port=8989" --env TOOL_OPTS="-Ddw.graphhopper.datareader.file=/data/herault.osm.pbf -Ddw.graphhopper.graph.location=herault-gh" --entrypoint /bin/bash israelhikingmap/graphhopper -c "wget https://testpg.pagesperso-orange.fr/files/herault.pbf -O /data/herault.osm.pbf && java -Ddw.graphhopper.datareader.file=/data/herault.osm.pbf -Ddw.graphhopper.graph.location=herault-gh -jar *.jar server config-example.yml"`

When I log into the container (with `docker exec -it GHCONTAINER bash`), I can check that all seems to work well (i.e. I can execute `wget localhost:8989`), but not from localhost.
I've found that I should comment out the bind_host lines in config-example.yml : https://discuss.graphhopper.com/t/how-to-connect-to-graphhopper/4470/6

But if I modify the config file on the running GH container, I don't how to restart the server. And I don't either how I could re-build the image with the modified config-example.yml : please could you help me to solve this ? Thanks

**Comment by PatGendre** [comment] 2022-02-16 15:50
I use this image https://hub.docker.com/r/israelhikingmap/graphhopper
so it seems version 5.0 as when I run the image I have this log
[main] INFO  com.graphhopper.GraphHopper - version 5.0|2022-01-26T02:02:20Z (8,21,6,5,6,8)

**Comment by PatGendre** [comment] 2022-02-16 15:51
I could use version 3.0, no problem, it's just for a test, currently.

**Comment by HarelM** [comment] 2022-02-16 18:16
It's hard to tell what the problem is from the above details.
You need to see that the server is ready to receive requests.
We are using this image in production so I'm certain it's working properly. Might be some docker configurations I guess...

**Comment by PatGendre** [comment] 2022-02-16 19:24
As I told you, the server is working. I can request pages to localhost:8989 from the container bash.
But not from the (debian) host.
I do `'wget localhost:8989'`, I get a `read error (connection reset by peer) in headers`
A docker ps -a returns
```
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
04eb1f3f1809   israelhikingmap/graphhopper   "/bin/bash -c 'wget …"   35 minutes ago   Up 35 minutes (healthy)   0.0.0.0:8989->8989/tcp, :::8989->8989/tcp   infallible_brattain
```
I if I do `docker port` for the container, I get 
```
8989/tcp -> 0.0.0.0:8989
8989/tcp -> :::8989
```


As you may have guessed, I am not a system engineer. I've found in the forum that commenting out the `bind_host : localhost ` line in the config file would solve the problem. But I cannot really try as I don't know how to restart the server once the container is active, and I don't know either how I could build the container.

**Comment by PatGendre** [comment] 2022-02-17 07:44
As I told you, the server is working. I can request pages to localhost:8989 from the container bash.
But not from the (debian) host.
I do `'wget localhost:8989'`, I get a `read error (connection reset by peer) in headers`
A docker ps -a returns
```
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
04eb1f3f1809   israelhikingmap/graphhopper   "/bin/bash -c 'wget …"   35 minutes ago   Up 35 minutes (healthy)   0.0.0.0:8989->8989/tcp, :::8989->8989/tcp   infallible_brattain
```
I if I do `docker port` for the container, I get 
```
8989/tcp -> 0.0.0.0:8989
8989/tcp -> :::8989
```


As you may have guessed, I am not a system engineer. I've found in the forum that commenting out the `bind_host : localhost ` line in the config file would solve the problem. But I cannot really try as I don't know how to restart the server once the container is active, and I don't know either how I could build the container.

**Comment by rkube-rvk** [comment] 2022-02-17 10:39
Hi @PatGendre,

I looked again to this issue and you already provided the (for me right) answer:
> I've found that I should comment out the bind_host lines in config-example.yml : https://discuss.graphhopper.com/t/how-to-connect-to-graphhopper/4470/6

You asked:
> But I cannot really try as I don't know how to restart the server once the container is active, and I don't know either how I could build the container.

There are more than one way to do this. Good news: You don't need to rebuild the image.
Maybe the fastest(?) way is to put your fixed config from your PC to a volume and refere this file  then at the entrypoint:

`docker volume create graphhopper-config     # Create a named volume.`
`docker run --rm --name dummy --volume graphhopper-config:/data-config alpine tail -f /dev/null         # Run a dummy container to acces the volume in it.`
`docker cp <Edited config-example.yml file on your PC> dummy:/data-config/   # Copy the edited config file to the volume`
`docker stop dummy    # Stop dummy container`

After this please start the container with a minimal adopted run command:

`docker run --volume graphhopper-config:/data-config --entrypoint /bin/bash israelhikingmap/graphhopper -c "wget https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O /data/berlin.osm.pbf && java -Ddw.graphhopper.datareader.file=/data/berlin.osm.pbf -Ddw.graphhopper.graph.location=berlin-gh -jar *.jar server /data-config/config-example.yml"`


Disclaimer: Pardon me please, this is my first time trying to add information to an issue on github, with docker, ... :-)

**Comment by HarelM** [comment] 2022-02-17 10:59
The host_bind is a tricky part.
I've added this to the latest readme and updated the instructions.
A new image will be created tomorrow morning with the latest changes and the new graphhopper.sh file.
If all goes well it should be much easier to use it.
Closing this for now as it should've been addressed in the latest PR I just merged.
Feel free to continue the discussion here.

**Closed by HarelM** 2022-02-17 10:59 UTC

**Comment by HarelM** [comment] 2022-02-17 16:57
In the image tomorrow you should be able to use --host 0.0.0.0

**Comment by PatGendre** [comment] 2022-03-10 11:18
@HarelM Thanks, it worked sorry for the delay before testing again
I bind mounted a data-conf directory with the pre-loaded pbf file and the config-example.yml file with the bind_host 0.0.0.0 line commented out,
so the command line looks like this for me in the end:
```
docker run -p 8989:8989 -v "$PWD"/data-conf:/data-conf --env JAVA_OPTS="-Xmx1g -Xms1g -Ddw.server.application_connectors[0].bind_host=0.0.0.0 -Ddw.server.application_connectors[0].port=8989" --env TOOL_OPTS="-Ddw.graphhopper.datareader.file=/data-conf/herault.pbf -Ddw.graphhopper.graph.location=herault-gh" --entrypoint /bin/bash israelhikingmap/graphhopper -c "
java -Ddw.graphhopper.datareader.file=/data-conf/herault.pbf -Ddw.graphhopper.graph.location=herault-gh -jar *.jar server /data-conf/config-example.yml"
```
